# Defining Libraries
from nwosimplib import *
from nwosimplib import socket

# Hostname and IP configuration
hostname = socket.gethostname()
IPAddr = socket.gethostbyname(hostname)

# Defining the CLEAR function
def clear():

    # For NT-based clients (Windows):
    if name == 'nt':
        _ = system('cls')

    # For UNIX systems (Linux, MacOS, etc. os.name is 'posix')
    else:
        _ = system('clear')

# Defining Startup (entirely aesthetic)
def kernelbootload():

    # Stage One: Locating Kernel
    clear()
    print('Locating Kernel.')
    time.sleep(1)
    clear()
    print('Locating Kernel..')
    time.sleep(1)
    clear()
    print('Locating Kernel...')
    time.sleep(1)
    clear()
    print('Locating Kernel.')
    time.sleep(1)
    clear()
    print('Locating Kernel..')
    time.sleep(1)
    clear()
    print('Locating Kernel...')
    time.sleep(1)
    clear()

    # Stage Two: Loading OS

    print('Kernel found, "NightwolfOS v1.0" now loading.')
    time.sleep(0.5)
    clear()
    print('Kernel found, "NightwolfOS v1.0" now loading..')
    time.sleep(0.5)
    clear()
    print('Kernel found, "NightwolfOS v1.0" now loading...')
    time.sleep(0.5)
    clear()
    print('Kernel found, "NightwolfOS v1.0" now loading.')
    time.sleep(0.5)
    clear()
    print('Kernel found, "NightwolfOS v1.0" now loading..')
    time.sleep(0.5)
    clear()
    print('Kernel found, "NightwolfOS v1.0" now loading...')
    time.sleep(0.5)
    clear()

    # Stage Three: Starting OS

    print('Kernel loaded! Starting OS now!')
    time.sleep(3)
    clear()
def biosstart():
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries.')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries..')
    print('')
    time.sleep(.1)
    clear()
    print('Your Computer name is: '+hostname)
    print('')
    print('Your IP address is: '+IPAddr)
    print('')
    print(f'Memory: {psutil.virtual_memory}')
    print('')
    print('Loading Libraries...')
    print('')
    time.sleep(.1)
def iplog():
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('Logging IP Address.')
    time.sleep(.1)
    clear()
    print('Logging IP Address..')
    time.sleep(.1)
    clear()
    print('Logging IP Address...')
    time.sleep(.1)
    clear()
    print('IP Addr logged successfully, booting.')
    time.sleep(1.5)
